services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672" # Management UI
      - "5672:5672"   # AMQP port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - mq_network

  producer:
    build:
      context: ./MessageProducer
      dockerfile: Dockerfile
    container_name: producer
    ports:
      - "8081:8081"
    networks:
      - mq_network
    depends_on:
      - rabbitmq

  consumer:
    build:
      context: ./MessageConsumer
      dockerfile: Dockerfile
    container_name: consumer
    ports:
      - "8082:8082"
    networks:
      - mq_network
    depends_on:
      - producer

volumes:
  rabbitmq_data:

networks:
  mq_network:
    driver: bridge
